//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tatais.DMX {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class frmSimples_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal frmSimples_() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tatais.DMX.frmSimples.", typeof(frmSimples_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group Color.
        /// </summary>
        public static string GroupColor {
            get {
                return ResourceManager.GetString("GroupColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group Control.
        /// </summary>
        public static string GroupControl {
            get {
                return ResourceManager.GetString("GroupControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load Program.
        /// </summary>
        public static string LoadAutoFile {
            get {
                return ResourceManager.GetString("LoadAutoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preset 1.
        /// </summary>
        public static string Preset1 {
            get {
                return ResourceManager.GetString("Preset1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preset 2.
        /// </summary>
        public static string Preset2 {
            get {
                return ResourceManager.GetString("Preset2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color Unit 1.
        /// </summary>
        public static string SelectColorUnit1 {
            get {
                return ResourceManager.GetString("SelectColorUnit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color Unit 2.
        /// </summary>
        public static string SelectColorUnit2 {
            get {
                return ResourceManager.GetString("SelectColorUnit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color Unit 3.
        /// </summary>
        public static string SelectColorUnit3 {
            get {
                return ResourceManager.GetString("SelectColorUnit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color Unit 4.
        /// </summary>
        public static string SelectColorUnit4 {
            get {
                return ResourceManager.GetString("SelectColorUnit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color Unit 5.
        /// </summary>
        public static string SelectColorUnit5 {
            get {
                return ResourceManager.GetString("SelectColorUnit5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color Unit 6.
        /// </summary>
        public static string SelectColorUnit6 {
            get {
                return ResourceManager.GetString("SelectColorUnit6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color Unit 7.
        /// </summary>
        public static string SelectColorUnit7 {
            get {
                return ResourceManager.GetString("SelectColorUnit7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color Unit 8.
        /// </summary>
        public static string SelectColorUnit8 {
            get {
                return ResourceManager.GetString("SelectColorUnit8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Auto Program.
        /// </summary>
        public static string StartAutoFile {
            get {
                return ResourceManager.GetString("StartAutoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        public static string StartConnection {
            get {
                return ResourceManager.GetString("StartConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop Auto Program.
        /// </summary>
        public static string StopAutoFile {
            get {
                return ResourceManager.GetString("StopAutoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        public static string StopConnection {
            get {
                return ResourceManager.GetString("StopConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LED Unit 1.
        /// </summary>
        public static string Unit1 {
            get {
                return ResourceManager.GetString("Unit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LED Unit 2.
        /// </summary>
        public static string Unit2 {
            get {
                return ResourceManager.GetString("Unit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LED Unit 3.
        /// </summary>
        public static string Unit3 {
            get {
                return ResourceManager.GetString("Unit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LED Unit 4.
        /// </summary>
        public static string Unit4 {
            get {
                return ResourceManager.GetString("Unit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LED Unit 5.
        /// </summary>
        public static string Unit5 {
            get {
                return ResourceManager.GetString("Unit5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LED Unit 6.
        /// </summary>
        public static string Unit6 {
            get {
                return ResourceManager.GetString("Unit6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LED Unit 7.
        /// </summary>
        public static string Unit7 {
            get {
                return ResourceManager.GetString("Unit7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LED Unit 8.
        /// </summary>
        public static string Unit8 {
            get {
                return ResourceManager.GetString("Unit8", resourceCulture);
            }
        }
    }
}
